include:
 - project: acc-co/devops/python/acc-py-devtools
   file: acc_py_devtools/templates/gitlab-ci/python.yml

before_script:
 - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.cern.ch".insteadOf https://:@gitlab.cern.ch:8443


GUI Tests:
  image: gitlab-registry.cern.ch/acc-co/accsoft/gui/accsoft-gui-pyqt-distro/acc-py-pyqt:ci
  script:
   - source /opt/venv/bin/activate
   - pip install .[core,test]
   - cd be_bi_pyqt_template
   - pyqt5ac --config pyqt5ac.yml
   - cd ../
   - run_headless python -m pytest --log-cli-level=DEBUG --random-order --junitxml=report.xml  \
     --cov-report html:coverage --cov-report term-missing:skip-covered --cov=be_bi_pyqt_template
     \ -vx --color=yes
  coverage: /TOTAL.+ ([0-9]{1,3}%)/
  artifacts:
    name: coverage-report
    paths:
     - coverage
    when: on_success
    expire_in: 1 month
    reports:
      junit: report.xml


# A dev build of the documentation, made available through cern.ch/acc-py.
Build Docs:
  extends: .acc_py_build_docs


# A release build of the documentation, made available through cern.ch/acc-py.
Build Docs On Tag:
  extends: .acc_py_build_docs_on_tag
