include:
  - project: 'acc-co/devops/python/acc-py-devtools'
    file: 'acc_py_devtools/templates/gitlab-ci/python.yml'

before_script:
  - source /opt/venv/bin/activate
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.cern.ch".insteadOf https://:@gitlab.cern.ch:8443

gui_tests:
  image: gitlab-registry.cern.ch/acc-co/accsoft/gui/accsoft-gui-pyqt-distro/acc-py-pyqt:ci
  script:
    - pip install .[core,test]
    - run_headless python -m pytest --log-cli-level=DEBUG --random-order --junitxml=report.xml  \
      --cov-report html:coverage --cov-report term-missing:skip-covered --cov=be_bi_application_frame \
      -vx --color=yes
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    name: coverage-report
    paths:
      - coverage
    when: on_success
    expire_in: 1 month
    reports:
      junit: report.xml
